
name = 'tests'

from tests.SMA_test import SMATest
from tests.EMA_test import EMATest
from tests.MACD_test import MACDTest
from tests.RSI_test import RSITest
from tests.Momentum_test import MomentumTest
from tests.ROC_test import ROCTest
from tests.Acceleration_test import AccelerationTest
from tests.StdDeviation_test import StdDeviationTest
from tests.BollingerBands_test import BollingerBandsTest
from tests.ATR_test import ATRTest
from tests.AccumulationDistribution_test import AccumulationDistributionTest
from tests.AccumulativeSwingIndex_test import AccumulativeSwingIndexTest
from tests.ALMA_test import ALMATest
from tests.AO_test import AOTest
from tests.BOP_test import BOPTest
from tests.PPO_test import PPOTest
from tests.RVGI_test import RVGITest
from tests.RVI_test import RVITest
from tests.Stochastic_test import StochasticTest
from tests.VO_test import VOTest
from tests.OBV_test import OBVTest
from tests.PVT_test import PVTTest
from tests.MassIndex_test import MassIndexTest
from tests.CMF_test import CMFTest
from tests.DPO_test import DPOTest
from tests.PC_test import PCTest
from tests.NetVolume_test import NetVolumeTest
from tests.KST_test import KSTTest
from tests.TSI_test import TSITest
from tests.WilliamsR_test import WilliamsRTest
from tests.Envelope_test import EnvelopeTest
from tests.EOM_test import EOMTest
from tests.ChandeMO_test import ChandeMOTest
from tests.ChaikinOsc_test import ChaikinOscTest
from tests.CoppockCurve_test import CoppockCurveTest
from tests.VWMA_test import VWMATest
from tests.VWAP_test import VWAPTest
from tests.WMA_test import WMATest
from tests.DC_test import DCTest
from tests.StochasticRSI_test import StochasticRSITest
from tests.TRIX_test import TRIXTest
from tests.EMAVolume_test import EMAVolumeTest
