name = 'HFStrategy'

from HFIndicators.indicator import Indicator
from HFIndicators.ema import EMA
from HFIndicators.rsi import RSI
from HFIndicators.roc import ROC
from HFIndicators.accumulation_distribution import AccumulationDistribution
from HFIndicators.acceleration import Acceleration
from HFIndicators.alma import ALMA
from HFIndicators.atr import ATR
from HFIndicators.accumulative_swing_index import AccumulativeSwingIndex
from HFIndicators.sma import SMA
from HFIndicators.awesome_oscillator import AO
from HFIndicators.balance_of_power import BOP
from HFIndicators.stddev import StdDeviation
from HFIndicators.bbands import BollingerBands
from HFIndicators.chaikin_money_flow import CMF
from HFIndicators.chaikin_oscillator import ChaikinOsc
from HFIndicators.chande_momentum_oscillator import ChandeMO
from HFIndicators.wma import WMA
from HFIndicators.coppock_curve import CoppockCurve
from HFIndicators.detrended_price_oscillator import DPO
from HFIndicators.donchian_channels import DC
from HFIndicators.ease_of_movement import EOM
from HFIndicators.ema_vol import EMAVolume
from HFIndicators.envelope import Envelope
from HFIndicators.know_sure_thing import KST
from HFIndicators.macd import MACD
from HFIndicators.mass_index import MassIndex
from HFIndicators.momentum import Momentum
from HFIndicators.net_volume import NetVolume
from HFIndicators.on_balance_volume import OBV
from HFIndicators.price_channel import PC
from HFIndicators.price_oscillator import PPO
from HFIndicators.price_volume_trend import PVT
from HFIndicators.relative_vigor_index import RVGI
from HFIndicators.relative_volatility_index import RVI
from HFIndicators.williams_r import WilliamsR
from HFIndicators.vwma import VWMA
from HFIndicators.vwap import VWAP
from HFIndicators.volume_oscillator import VO
from HFIndicators.true_strength_index import TSI
from HFIndicators.trix import TRIX
from HFIndicators.stochastic import Stochastic
from HFIndicators.stochastic_rsi import StochasticRSI